import { LocalWalletProvider } from '@/providers/wallet-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GameContext } from '@/providers/game-provider'
import { Keypair } from '@solana/web3.js'
import { useState } from 'react'
import { Wallet } from '@project-serum/anchor'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocalWalletProvider>
          {children}
        </LocalWalletProvider>
      </body>
    </html>
  )
}
