[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe_program = "DWFkjLba8qu1fmAxHC88jktCDS2LA5JzVTbR447Pccyt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/siddharthagarwal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
