[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe_program = "CZtPmzEjnWzSa4MWzxBLrsc6mw1AgqhTHBgAsdzJ1Jv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/siddharthagarwal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
